module.exports = [
  {
    title: "Développeur full-stack",
    description: "Clementine",
    date: "Depuis Juin 2019",
    mobileStyle: "width: 10rem; position: relative; left: -5px;",
    logoPath: "experience/clementine.png",
    icon: "briefcase",
    tasks: [
      "Refonte en Typescript de l'application client de comptabilité",
      "Gridsome - Mise à jour du site web",
    ],
  },
  {
    title: "Bootcamp de développement web",
    description: "The hacking project",
    date: "Octobre 2018",
    mobileStyle: "width: 10rem; position: relative; left: -5px;",
    logoPath: "experience/thp.png",
    icon: "graduation-cap",
    tasks: [
      "Travail en équipe via Git et Github",
      " Algorithmie avec des programmes en Ruby",
      "Réalisation de sites dynamiques avec Rails",
      "Frontend avec HTML / CSS et JavaScript",
      "Projets complexes en équipe",
    ],
  },
  {
    title: "Tireur filtreur",
    description: "Négatif plus",
    date: "Octobre 2015 - Octobre 2017",
    mobileStyle: "width: 10rem; position: relative; left: -5px;",
    logoPath: "experience/negatif-plus.png",
    icon: "briefcase",
    tasks: [
      "Développement noir & blanc sur Transfer",
      "Tirage couleur MiniLab",
    ],
  },
  {
    title: "BTM Photographie",
    description: "Chambre des métiers et de l'artisanat du Gard",
    date: "Octobre 2015 - Octobre 2017",
    mobileStyle: "width: 10rem;",
    logoPath: "experience/cma.png",
    icon: "graduation-cap",
    tasks: [
      "Histoire de la photographie",
      "Prise de vue en studio",
      "Animation d'équipe",
      "Innovation commerciale",
    ],
  },
  {
    title: "Photographe culturel",
    description: "Archives Nationales d'Outre-mer",
    date: "Octobre 2015 - Octobre 2017",
    mobileStyle: "width: 10rem; position: relative; left: -5px;",
    logoPath: "experience/anom.png",
    icon: "briefcase",
    tasks: [
      "Numérisation sur banc de reproduction",
      "Reportage vie d'entreprise",
      "Contrôle qualité numérisation prestataire",
    ],
  },
  {
    title: "Licence Communication, médiation numérique",
    description: "Université Paul Valéry - Montpellier",
    date: "2011 - 2015",
    mobileStyle: "width: 10rem; position: relative; left: 0px;",
    logoPath: "experience/um3.png",
    icon: "graduation-cap",
    tasks: [
      "Ingénierie éditoriale - Adobe InDesign",
      "Sémiologie de l'image",
      "Médiation culturelle",
    ],
  },
];
